# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offthegridapp', '0003_auto_20160421_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='num_events',
        ),
        migrations.AddField(
            model_name='vendor',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offthegridapp.Event'),
            preserve_default=False,
        ),
    ]
