# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offthegridapp', '0004_auto_20160421_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_vendors',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
