# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offthegridapp', '0006_auto_20160421_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='event_identification',
        ),
    ]
